package pe.edu.upeu.navegationjpc.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val green_primaryLight = Color(0xFF006A68)
val green_onPrimaryLight = Color(0xFFFFFFFF)
val green_primaryContainerLight = Color(0xFF9CF1EF)
val green_onPrimaryContainerLight = Color(0xFF00504F)
val green_secondaryLight = Color(0xFF4A6362)
val green_onSecondaryLight = Color(0xFFFFFFFF)
val green_secondaryContainerLight = Color(0xFFCCE8E6)
val green_onSecondaryContainerLight = Color(0xFF324B4A)
val green_tertiaryLight = Color(0xFF4A607C)
val green_onTertiaryLight = Color(0xFFFFFFFF)
val green_tertiaryContainerLight = Color(0xFFD2E4FF)
val green_onTertiaryContainerLight = Color(0xFF334863)
val green_errorLight = Color(0xFFBA1A1A)
val green_onErrorLight = Color(0xFFFFFFFF)
val green_errorContainerLight = Color(0xFFFFDAD6)
val green_onErrorContainerLight = Color(0xFF93000A)
val green_backgroundLight = Color(0xFFF4FBF9)
val green_onBackgroundLight = Color(0xFF161D1C)
val green_surfaceLight = Color(0xFFF4FBF9)
val green_onSurfaceLight = Color(0xFF161D1C)
val green_surfaceVariantLight = Color(0xFFDAE5E3)
val green_onSurfaceVariantLight = Color(0xFF3F4948)
val green_outlineLight = Color(0xFF6F7978)
val green_outlineVariantLight = Color(0xFFBEC9C7)
val green_scrimLight = Color(0xFF000000)
val green_inverseSurfaceLight = Color(0xFF2B3231)
val green_inverseOnSurfaceLight = Color(0xFFECF2F1)
val green_inversePrimaryLight = Color(0xFF80D5D3)
val green_surfaceDimLight = Color(0xFFD5DBDA)
val green_surfaceBrightLight = Color(0xFFF4FBF9)
val green_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val green_surfaceContainerLowLight = Color(0xFFEFF5F4)
val green_surfaceContainerLight = Color(0xFFE9EFEE)
val green_surfaceContainerHighLight = Color(0xFFE3E9E8)
val green_surfaceContainerHighestLight = Color(0xFFDDE4E3)

//modo noche
val green_primaryDark = Color(0xFF80D5D3)
val green_onPrimaryDark = Color(0xFF003736)
val green_primaryContainerDark = Color(0xFF00504F)
val green_onPrimaryContainerDark = Color(0xFF9CF1EF)
val green_secondaryDark = Color(0xFFB0CCCA)
val green_onSecondaryDark = Color(0xFF1B3534)
val green_secondaryContainerDark = Color(0xFF324B4A)
val green_onSecondaryContainerDark = Color(0xFFCCE8E6)
val green_tertiaryDark = Color(0xFFB2C8E8)
val green_onTertiaryDark = Color(0xFF1B324B)
val green_tertiaryContainerDark = Color(0xFF334863)
val green_onTertiaryContainerDark = Color(0xFFD2E4FF)
val green_errorDark = Color(0xFFFFB4AB)
val green_onErrorDark = Color(0xFF690005)
val green_errorContainerDark = Color(0xFF93000A)
val green_onErrorContainerDark = Color(0xFFFFDAD6)
val green_backgroundDark = Color(0xFF0E1514)
val green_onBackgroundDark = Color(0xFFDDE4E3)
val green_surfaceDark = Color(0xFF0E1514)
val green_onSurfaceDark = Color(0xFFDDE4E3)
val green_surfaceVariantDark = Color(0xFF3F4948)
val green_onSurfaceVariantDark = Color(0xFFBEC9C7)
val green_outlineDark = Color(0xFF889392)
val green_outlineVariantDark = Color(0xFF3F4948)
val green_scrimDark = Color(0xFF000000)
val green_inverseSurfaceDark = Color(0xFFDDE4E3)
val green_inverseOnSurfaceDark = Color(0xFF2B3231)
val green_inversePrimaryDark = Color(0xFF006A68)
val green_surfaceDimDark = Color(0xFF0E1514)
val green_surfaceBrightDark = Color(0xFF343A3A)
val green_surfaceContainerLowestDark = Color(0xFF090F0F)
val green_surfaceContainerLowDark = Color(0xFF161D1C)
val green_surfaceContainerDark = Color(0xFF1A2120)
val green_surfaceContainerHighDark = Color(0xFF252B2B)
val green_surfaceContainerHighestDark = Color(0xFF2F3636)